version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-react-app
    container_name: my-react-app
    restart: unless-stopped
    ports:
      - "3000:3000"
